[package]
name = "common"
version = "0.1.0"
authors = ["Michael de Lang <kingoipo@gmail.com>"]

[[test]]
name = "test"
path = "test/test.rs"

[dependencies]
serde = "0.8"
serde_macros = "0.8"
serde_json = "0.8"
